### ISSUE TITLE
Missing libSDL2_gfx-1.0.so.0 library error with ArkOS on 351P

### ISSUE THREAD

**Issue by romadu** [Tardigrade-nx/351Files#1]
After installing on ArkOS on 351P I get this error. I can find this library in `/usr/lib/arm-linux-gnueabihf`

`./351Files: error while loading shared libraries: libSDL2_gfx-1.0.so.0: cannot open shared object file: No such file or directory`

**Comment by Tardigrade-nx** [comment]
It should be fixed in v1.1. I can't be sure though, because I dont have a RG351P to test on.

**Comment by romadu** [comment]
It's working now, thanks
